### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jbovenschen**
After merging #1339 this project does have a dependency.

I think it is better to remove the "and has no dependencies" from the README.md.
Maybe it would be better to explain why lodash is added as a dependency.

### CODE REVIEW

**Comment by gaearon** [comment]
Yeah, this came up before. Technically it has a dependency but we are talking about two ten-line files, not the *whole* Lodash. We use just those two modules, and similar code was previously bundled into Redux, so there is no sensible size difference.

Can we reword it in a way that suggests that *it’s 2kB including the dependencies*? This way we make it clear Lodash doesn’t make the build large.

**Comment by jbovenschen** [comment]
I guess it would be nice to have a sentence something like the following; 
It is tiny (2kB) including lodash utilities. ?

Because it makes it more clear that it has just one dependency that is lodash and it is using lodash for providing utility functions from lodash.

**Comment by gaearon** [comment]
I don’t want to mention Lodash specifically. That we are using it is an implementation detail nobody should worry or care about.

Maybe like this?

>It is tiny, even when bundled with the dependencies (2kB).

**Comment by acdlite** [comment]
> It is tiny (2kB, including dependencies).

?

**Comment by gaearon** [comment]
@acdlite :+1:

**Comment by jbovenschen** [comment]
I think that one is great i will change it tonight!

**Comment by gaearon** [comment]
:+1:

**Pull request merged**
