### PR TITLE
Rackt eslint config

### PR DESCRIPTION
**Pull request by ellbee**
So, erm, this is quite a big one. It addresses issue #958. Files in src, test and examples pass the lint and I pulled out each bit of code from the docs and checked that they also passed the lint.

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like this got outdated with some recent merge. Can you please update?

**Comment by ellbee** [comment]
Ok, should be up to date now.

**Comment by gaearon** [comment]
Man, I'm sorry to bug you, can you resolve again?
I leave it to you to actually merge it right after that, so we don't get out of sync again.

**Comment by ellbee** [comment]
Ha ha, yeah, no problem. Weirdly, I have started to sort of enjoy linting. :flushed:

**Pull request merged**
