### PR TITLE
Add section on unit testing middleware to docs

### PR DESCRIPTION
**Pull request by idolize**
Updated `WritingTests.md` with a section on how to test middleware.

The function signature for middlware is a little confusing, so I think this could add a lot of value.

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks

**Comment by gsklee** [comment]
Can we expand upon this part a little bit more? Like what's inside `singleDispatch.js` and an example `actions.js` showing how the `singleDispatch` middleware is being used in the code.

**Comment by tristanls** [comment]
What is `singleDispatch.js`? This example is extremely confusing. Is this fictional middleware? Am I supposed to know how to implement this module? The string `singleDispatch` only occurs in the doc file and nowhere else in this repo.

**Comment by markerikson** [comment]
Yeah, it appears to be a fictional middleware that is referenced in the unit test examples, but not actually shown anywhere.

**Comment by tristanls** [comment]
I ended up using [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store) for testing dispatch.

**Comment by IndependentContractor** [comment]
Has anyone figured out how to implement `singleDispatch` or what it might look like?

**Comment by brigand** [comment]
@IndependentContractor my guess is that it'd either be one dispatch ever, or one dispatch per action type.

```js
let dispatched = true;
singleDispatch = store)=> next => action => {
  if (dispatched) return;
  dispatched = true;
  next(action);
}
```

```js
let dispatchedTypes = new Map();
singleDispatch = store)=> next => action => {
  if (dispatchedTypes.get(action.type)) return;
  dispatchedTypes.set(action.type, true);
  next(action);
}
```

**Comment by brigand** [comment]
I'm going to take a stab at improving these docs.

**Comment by brigand** [comment]
#2496

**Pull request merged**
