### PR TITLE
wording: combineReducers.md

### PR DESCRIPTION
**Pull request by chentsulin**
may -> must

### CODE REVIEW

**Comment by gaearon** [comment]
AFAIK "may never" is a correct form...
Summoning English native speakers to this thread. :gb:

**Comment by chentsulin** [comment]
I am not sure for this, but just want to correspond to `the initial state must not be undefined either`. If any native speakers could give a lesson here is also great, haha

**Comment by ronag** [comment]
`must` or `shall` are the usual terms in requirements specification.

**Comment by ronag** [comment]
`If the `state` given to it is `undefined` it must return the initial state for this specific reducer which, according to the previous rule, also must not be `undefined`.`

**Pull request merged**
