### PR TITLE
Use ES6 syntax and the spread operator

### PR DESCRIPTION
**Pull request by mjethani**
I'm just trying to make it consistent with the rest of the documentation.

You can view the first diff with the `--ignore-space-change` option to `git-diff`.

### CODE REVIEW

**Comment by simplesmiler** [comment]
Object spread operator is ES7, if I recall correctly.

**Comment by gaearon** [comment]
I don't mind changing the middleware to use arrows but please don't use object spread operator. Unlike array spread operator it's not part of ES6.

**Comment by mjethani** [comment]
The object spread operator is all over the Redux documentation (esp. reducers). Are the rules different for middleware?

**Comment by simplesmiler** [comment]
@mjethani I believe you are confusing array spread `[ ...a ]` and object spread `{ ...a }`.

**Comment by mjethani** [comment]
@simplesmiler No, the [section on reducers](http://rackt.org/redux/docs/basics/Reducers.html) specifically mentions and encourages the use of the ES7 object spread operator. It says: "You can also enable the experimental object spread syntax proposed for ES7 to write `{ ...state, ...newState }` instead." It's used in all the subsequent reducer examples.

**Comment by gaearon** [comment]
If it used further below it is a mistake. We don't want to use it in docs other than mention it in that sentence you quoted and the code snippet immediately afterwards that demonstrates it

**Comment by mjethani** [comment]
Now I see that it is in fact the array spread operator that's used in the examples. The reducers documentation is fine then. I'll make the necessary change to this one.

**Comment by mjethani** [comment]
Done.

**Comment by alucic** [comment]
@mjethani @gaearon you can `--ignore-space-change` on github by adding `?w=1` to your files url
https://github.com/rackt/redux/pull/1109/files?w=1

https://github.com/blog/967-github-secrets#whitespace

**Comment by gaearon** [comment]
Thanks

**Pull request merged**
