### PR TITLE
text property missing

### PR DESCRIPTION
**Pull request by raunaqrox**

### CODE REVIEW

**Comment by sbusch** [comment]
{ text } is a valid object literal in ES6 (which AFAIK all examples are using) and equivalent to { text: text }

See https://github.com/lukehoban/es6features#enhanced-object-literals

**Comment by gaearon** [comment]
Yeah, it's ES6 property shorthand syntax.

**Comment by raunaqrox** [comment]
sorry I didn't know.

**Comment by gaearon** [comment]
No problem! :+1: 
Great resource on ES6: https://leanpub.com/understandinges6/read

**Comment by raunaqrox** [comment]
Thanks!

**Pull request closed without merging**
