### PR TITLE
adds documentation for exampleTodoList file structure and up & running

### PR DESCRIPTION
**Pull request by alanbsmith**
### OVERVIEW
This PR adds documentation to ExampleTodoList.md. Specifically it lists the file structure of the app and how to get it up and running.

### WHY?
While the documentation is really great for this example, it would be useful to have an overview of the file structure (what goes where) and also what other files are needed to get it up and running. This just makes that process more approachable.

### CLOSING
I tried to follow the Markdown conventions already present, but if something needs to be changed/improved, please let me know! I'll be happy to fix it.

### CODE REVIEW

**Comment by gaearon** [comment]
Hey, thanks for the PR! We actually added `todos-with-undo` example which is *almost* identical to this tutorial, except it also features Undo/Redo that will be covered in #810. I think it would be better to highlight this instead, but that would be better to do in #810..

**Comment by alanbsmith** [comment]
Thanks for the quick response, @gaearon!

Yeah, I see the two are really similar. I didn't see a readme for `todos-with-undo`. Are you saying you'd rather have this added to the readme for `todos-with-undo`? It would maybe be helpful to at least have a link to that example so you can get an idea of the file structure.

Happy to do whatever though. :smile:

**Comment by gaearon** [comment]
I mean that I'd rather add the link to "Implementing Undo" recipe (to be added in #810) and mention `todos-with-undo` example both in `ExampleTodoList.md` and `UsageWithReact.md`. The idea is to explain that:

* This example is "continued" in "Implementing Undo" but it's out of scope of the basic tutorial
* The complete code example is available in the repo as `todos-with-undo` (but it includes changes from "Implementing Undo" to be more useful)

**Comment by alanbsmith** [comment]
gotcha. :+1: That makes sense.

**Comment by gaearon** [comment]
I'll close as per https://github.com/rackt/redux/pull/814#issuecomment-143595579, thanks for PR though!

**Pull request closed without merging**
