### PR TITLE
Docs example: Use Object.assign also for updating state.todos

### PR DESCRIPTION
**Pull request by johannes-photobox**
The current example throws a syntax error (unexpected token). Not sure if we can even use "...-syntax" in object literals? Maybe this example just got never checked. But please let me know if I'm wrong.

### CODE REVIEW

**Comment by just-boris** [comment]
Spread syntax is possible with ES7 extension.

That doc page already mentioned that you can use `Object.assign` instead, but generally spread looks more readable.

**Comment by gaearon** [comment]
Good call. We shouldn't use ES7 proposals in docs.

**Comment by just-boris** [comment]
@gaearon that's weird, because rest of the examples in this file still uses it.

Does that mean, that I can send a PR with replacement for them too?

**Comment by gaearon** [comment]
The rest of the examples use ES6 array spread operator, not ES7 object spread operator proposal.

**Comment by just-boris** [comment]
Ok, got it, that makes sense

**Pull request merged**
