### PR TITLE
Update counter examples' "Increment if odd" to increment on negative odd numbers too.

### PR DESCRIPTION
**Pull request by nelsonjchen**

### CODE REVIEW

**Comment by gaearon** [comment]
Fair enough. Can you also fix the regular `counter` example as well as all occurrences, if any, of this phrase in the docs (`md` files)?

**Comment by nelsonjchen** [comment]
Ah, I'm a newbie whose just perusing the documentation to understand Redux. But I'll give a quick look through the repo.

**Comment by nelsonjchen** [comment]
Updated PR. I also added a test for that in the fix for counter. As far as the rest of the repo, I can't find anything else with `/%.*2.*===.*1/`.

**Comment by gaearon** [comment]
Appreciated!

**Pull request merged**
