### PR TITLE
Update to lodash v4.2.0.

### LINKED ISSUE #1346: 3.2.0 Global not defined with in isPlainObject
screen shot 2016-02-01 at 4 55 12 pm

I'm building our app files with browserify, babel 6.4, envify, react-redux, react 0.14 and the bundles are throwing this error that global is not defined. I take it envify or loose envify is not factoring out the globals?

For now I have reverted to 3.1.7 of redux and 4.1.2 of react-redux but of course it would be nice to see a real fix.

### PR DESCRIPTION
**Pull request by jdalton**
This closes #1346.

### CODE REVIEW

**Comment by stoeffel** [comment]
How about including [`lodash.isPlainObject`](https://www.npmjs.com/package/lodash.isplainobject) instead of the complete lodash?

**Comment by gaearon** [comment]
@stoeffel It doesn't really matter because we import just that module.

**Comment by stoeffel** [comment]
Agreed.
We're not using redux directly, but we use react-dnd. 
We depend on react-dnd with a fixed dependency, but react-dnd depends on dnd-core (not fixed) and dnd-core depends on redux (not fixed).
Our webpack was configured to alias lodash to one global lodash, I guess the intention behind that was to reduce client-size. This lead to a failing build because we are still using lodash v3, which wouldn't have happened if redux would use `lodash.isPlainObject` or the dependencies in dnd-core and react-dnd was fixed.
But IMO we need to change that anyway, because other libs will probably update to lodash v4 soon.

**Comment by gaearon** [comment]
Yes, that's a big assumption to make.
Wanna send a PR to update Lodash in DnD?

**Comment by stoeffel** [comment]
> Wanna send a PR to update Lodash in DnD?

Will try to find some time to create a PR, but maybe someone will be faster.

**Pull request merged**
