### PR TITLE
Add note about combineReducers in AsyncActions documentation

### PR DESCRIPTION
**Pull request by salehe**
It is somehow hard to grasp what's going on at first sight, specially for someone not much familiar with ES6.
I tried to explain the combineReducers part and let the reader figure out the ES6 part :)

### CODE REVIEW

**Comment by gaearon** [comment]
I think that section is a bit too heavy now because the code snippet is followed by a note, and then the list. How about we move the note *before* the snippet, just below the section title, and put something like 

>#### Note

> This section assumes you understand reducer composition with [`combineReducers()`](/docs/api/combineReducers.md), as described in the [introduction to reducers](/docs/basics/Reducers.md#splitting-reducers). If you don’t, please read it first.

What do you say?

**Comment by salehe** [comment]
I agree. I've updated the commit to reflect this.

**Comment by gaearon** [comment]
Can you please make `combineReducers()` a link to its API reference?

**Comment by salehe** [comment]
Ofcourse :)

**Pull request merged**
