### PR TITLE
test docs updates for react 0.14

### PR DESCRIPTION
**Pull request by mjw56**
This has a couple updates for react 0.14 (not sure if you're updating docs for 0.14 yet though).

### CODE REVIEW

**Comment by gaearon** [comment]
We'll update after 0.14 is out, thank you.
Let's keep this hanging.

**Comment by timdorr** [comment]
@mjw56 Any chance you can resolve the merge conflicts (a rebase is fine)? Also, any other updates needed now that we've got a final 0.14?

**Comment by gaearon** [comment]
I'm pretty sure these are updated now.
Thanks for the PR though!

**Comment by mjw56** [comment]
:+1: sweet, thanks!

**Pull request closed without merging**
