### PR TITLE
Revert todos-with-undo being ported 0.14

### PR DESCRIPTION
**Pull request by gaearon**
We will update all examples at once when everything is ready.
Please, don't send PRs to update React to 0.14: #885

Project maintainers: please don't commit updates to 0.14 to master.
cc @omnidan

### CODE REVIEW

**Comment by omnidan** [comment]
Alright, sorry - didn't know we're waiting for something :grin:

**Comment by gaearon** [comment]
In the future it's better to create PRs. :wink: We don't want inconsistency in docs or examples, e.g. half website documenting 0.13 and half documenting 0.14.

**Comment by gaearon** [comment]
Also once we migrate to 0.14 we want examples to have no warnings. Currently DevTools, React Redux aren't ready.

**Comment by omnidan** [comment]
@gaearon yeah that makes sense - I'll create a PR next time.

**Comment by gaearon** [comment]
Superseded by https://github.com/rackt/redux/pull/901.

**Comment by gaearon** [comment]
I'd appreciate some help as described in https://github.com/rackt/redux/pull/901#issuecomment-148439804. Thanks!

**Pull request merged**
