### PR TITLE
Fix unhighlighted JavaScript code.

### PR DESCRIPTION
**Pull request by f**
This part was unhighlighted in documentation. I basically pushed the code into hl.js and wrote the output as HTML.

Keep up the good work!

### CODE REVIEW

**Comment by timdorr** [comment]
Since the HTML is generated, won't this be overridden by the next gitbook run?

Also, can you merge in #704 and #705 to this branch so we can track under one PR? Thanks!

**Comment by gaearon** [comment]
Unfortunately this indeed will be overridden next time we update the docs.

**Comment by gaearon** [comment]
All but one seem fixed with the new version of Highlight.js.
I filed an issue for the React part which is still not highlighted: https://github.com/isagalaev/highlight.js/issues/931

**Comment by gaearon** [comment]
Meh. I just ported the docs to use [Prism](http://prismjs.com) instead.
Looks much better now.

**Comment by f** [comment]
:+1: Better! Keep up good work guys!

**Pull request closed without merging**
