### PR TITLE
added reference to redux-mock-store in docs

### PR DESCRIPTION
**Pull request by arnaudbenard**
Hi,

I discussed with @gaearon yesterday on [Twitter](https://twitter.com/dan_abramov/status/658689636227792896) about extracting the mock store logic into a separate package. The benefits are that we can test the library and don't need to copy paste code around when the mock example is updated in the docs.

Here's the module: https://github.com/arnaudbenard/redux-mock-store

Let me know if you want to append changes/more tests to the current implementation and reference the package in the redux docs.

Thank you ;)

### CODE REVIEW

**Comment by omnidan** [comment]
@arnaudbenard looks good to me - you can also add it to the Ecosystem section (I'll keep this PR open in case you want to do that :wink:)

**Comment by arnaudbenard** [comment]
@omnidan Awesome. Should I create a `Testing` section or simply put it under `Utilities`?

**Comment by omnidan** [comment]
@arnaudbenard I would put it under `Utilities`, a section for just one module doesn't make sense (so: maybe later :smile:)

**Comment by arnaudbenard** [comment]
@omnidan done! Ready to merge :dancer:

**Comment by omnidan** [comment]
Thanks a lot! :grin:

**Pull request merged**
