### PR TITLE
Update examples and docs to React 0.14

### PR DESCRIPTION
**Pull request by gaearon**
Work in progress.

- [x] Release an update to React Redux @gaearon
- [x] Update all simple examples @gaearon
- [x] Update all docs @omnidan 
- [ ] Release an update to Redux DevTools @gaearon
- [ ] Update the real world example @gaearon
- [ ] Release an update to React Transform handling stateless components @gaearon
- [ ] Update examples to use the new React Transform @gaearon
- [ ] Convert components to be stateless where appropriate (we can do this as a separate pass later)

### CODE REVIEW

**Comment by gaearon** [comment]
I'd appreciate somebody making a PR *against this branch* to update all the `docs` to match the example updates I just pushed. Please keep the same code style and conventions. Where examples match the docs, it's best to use the exact code from examples.

If you intend to work on this, please write a comment in this PR so we don't duplicate the effort.

**Comment by omnidan** [comment]
@gaearon I already updated the `Implementing Undo History` you can just revert your revert commit for that

**Comment by omnidan** [comment]
I can work on updating the rest of the docs - the only things that need to be changed are `react-dom` and removing the function within `<Provider>`, right?

**Comment by gaearon** [comment]
@omnidan

That's why I wrote

>Please keep the same code style and conventions

There are two issues in that doc commit:

1. It uses `ReactDOM.render` over importing named `render`. Let's say it's my personal whim. :wink:
2. It uses `findDOMNode` where the call needs to be removed completely: DOM refs *are* nodes in 0.14.

**Comment by omnidan** [comment]
@gaearon aah okay - I'll do that then :smile:

**Comment by gaearon** [comment]
>I can work on updating the rest of the docs - the only things that need to be changed are react-dom and removing the function within <Provider>, right?

These two, and removing `findDOMNode` whenever it is already a DOM node—that is, pretty much everywhere it's used right now. For testing docs, it involves using `react` instead of `react/addons`, and using `react-addons-test-utils`.

**Comment by gaearon** [comment]
Thank you!

**Comment by omnidan** [comment]
In `applyMiddleware.md`: `React.renderToString` is used, but `React` isn't even imported - is this a mistake in the current version of the docs?

I would just import `renderToString` from `react-dom/server` and use that instead.

**Comment by gaearon** [comment]
@omnidan :+1: on what you suggested

**Comment by omnidan** [comment]
@gaearon alright, I updated the docs - only thing missing now are the tests. I'm too unsure about what to change there, maybe you should look into that :sweat_smile:

**Comment by omnidan** [comment]
Seems like the `React.addons.update` API changed too, so the link in `Troubleshooting.md` is broken right now (https://facebook.github.io/react/docs/update.html)

**Comment by omnidan** [comment]
`React.addons.update` isn't mentioned on https://facebook.github.io/react/docs/update.html which is linked in `Reducers.md` - not sure if that changed or is fine.

**Comment by gaearon** [comment]
It should be `react-addons-update` now.

**Comment by gaearon** [comment]
You can remove

```js
  // The child must be wrapped in a function
  // to work around an issue in React 0.13.
```

from UsageWithReact. Let's not leave traces of old API.

**Comment by omnidan** [comment]
@gaearon Done! I updated the other links in earlier commits (React -> ReactDOM, ReactDOMServer). Anything else, besides tests?

**Comment by gaearon** [comment]
This looks good to me, thank you for your help!

**Comment by gaearon** [comment]
This is good enough for now, so I'll merge and follow up in a second PR.
Everything but `real-world` is updated.

**Comment by omnidan** [comment]
Awesome! You're welcome :grin:

**Pull request merged**
