### PR TITLE
todo undo example - from click to on submit

### PR DESCRIPTION
**Pull request by tonyspiro**
Also removes ability to add an empty todo

### CODE REVIEW

**Comment by omnidan** [comment]
@tonyspiro Thanks! CI is failing (linter is complaining about something in your code), please check this.

**Comment by tonyspiro** [comment]
Thanks @omnidan, think I've got the issues fixed

**Comment by omnidan** [comment]
Looks good, thanks a lot @tonyspiro :grin: :+1:

**Comment by tonyspiro** [comment]
Thank you :metal:

**Pull request merged**
