### PR TITLE
Update ThreePrinciples.md

### PR DESCRIPTION
**Pull request by urbanvikingr**
Change `Mutations` with `Actions`. I had a discussion with another React developer and it seemed to be some confusing and it turned that it was caused by a misunderstanding of the concept of functional programming, pure functions and the use of the word `mutation`. I hope that this helps.

### CODE REVIEW

**Comment by sompylasar** [comment]
@urbanvikingr These are mutations, not actions -- the mutations to the state. You don't write actions as functions -- they are plain objects.

**Comment by urbanvikingr** [comment]
@sompylasar Mutation mean that you change the existing state, but Redux is creating a new state with the changes. I think that the word mutation gives some confusing. The text underneath clearly states that the Redux state tree is immutable.

**Comment by urbanvikingr** [comment]
I changed `Actions` to `Transformation`. I hope that this helps.

**Comment by sompylasar** [comment]
That makes more sense. Let's see what @gaearon thinks.

**Comment by gaearon** [comment]
Maybe just "changes are described by pure functions"?

**Comment by urbanvikingr** [comment]
I updated to `Changes are made with pure functions`, because it would be more readable, but I like `Changes are done by pure functions` too. I would just like to avoid using the word mutation. I hope that this helps.

**Comment by acdlite** [comment]
Action creators aren't necessarily pure

**Comment by urbanvikingr** [comment]
@acdlite The section is about Reducers :)

**Comment by acdlite** [comment]
Haha yes it is, was skimming through my notifications and got my wires crossed. Carry on :D

**Comment by ellbee** [comment]
Close to what @gaearon suggested, and reads nicely, so I think this can be merged. Thanks @urbanvikingr!

**Comment by urbanvikingr** [comment]
Thank you :)

**Pull request merged**
