### PR TITLE
Add permalink anchors to gitbook

### PR DESCRIPTION
**Pull request by jdlehman**
Solves part of Issue #345

### CODE REVIEW

**Comment by timdorr** [comment]
You actually don't need the plugin in the package.json file. Gitbook installs and maintains it for you. Can you update your commit with that removed? I think it should solve the merge conflict too.

**Comment by gaearon** [comment]
There are two more issues here:

* Last time I checked, the plugin didn't generate nice looking links like in React docs. We'd want to style them to be nicer.
* This issue makes anchor links semi-useless and it's better to fix it first https://github.com/GitbookIO/gitbook/issues/920

**Comment by jdlehman** [comment]
@timdorr cool didn't know that!

@gaearon Yeah... The anchors only work sometimes because of that issue.  I'll take a look at it.  I agree that the hover could use some custom styling.  Here is what it looks like by default:

anchors

**Comment by gaearon** [comment]
Closing for inactivity.
Would be happy to take this if it looked like in React docs.

screen shot 2015-12-12 at 18 34 50
screen shot 2015-12-12 at 18 34 53

**Pull request closed without merging**
