### PR TITLE
migrated examples/real-world to redux-simple-router

### PR DESCRIPTION
**Pull request by EmperorEarth**
This is my first contribution to this project.

I'm also not a programmer by trade, so I would encourage more experienced contributors to double-check that I didn't break anything.

### CODE REVIEW

**Comment by gaearon** [comment]
Thank you! There's already work in progress on this in https://github.com/rackt/redux/pull/1152. Anything missing there?

**Comment by EmperorEarth** [comment]
The code looks similar, aside some minor syntactical differences. I didn't see #1152.

I'm learning react/redux/react-router and used this as a learning exercise for redux-simple-router.

I would defer to Lassi's work. I'm sure he is more experienced.

**Comment by gaearon** [comment]
I'll look at both when I have some time. Thanks.

**Comment by EmperorEarth** [comment]
It looks like I failed Travis CI tests for omitting new lines at EOF.

Thanks for your contributions @gaearon! I'm building a social site, and your libraries should make my life much easier.

**Comment by timdorr** [comment]
Similar to https://github.com/rackt/redux/pull/1152#issuecomment-171146971:

`redux-simple-router` should go 2.0.0 in a day or two and comes with a much better API. Could you rework this based on that version when it comes out? Whomever gets to it first, wins! :smile:

**Pull request closed without merging**
