### PR TITLE
Changing Stateless components to default to function syntax instead of classes syntex

### PR DESCRIPTION
**Pull request by ajaybeniwal**
I have changed some examples folder to default stateless components to more cleaner new syntax introduced in react 0.14 , If you like you can merge the changes.

### CODE REVIEW

**Comment by timdorr** [comment]
Hmm, I'm kind of split on this. On the one hand, SFC's are cool and I'd love to see them used more. On the other hand, this raises the lowest common denominator (since they're so new and not as well-known as ES6 components) and are a tad slower (but that would be pre-optimization on our part).

I dunno, @gaearon what are you thoughts on this?

**Comment by gaearon** [comment]
I'm up for changing all examples to functional components where possible.

However I don't see why we need `react-stateless-wrapper`  I would like to avoid this dependency.

Also the comment is unnecessary, and there are some spacing inconsistencies.

**Comment by ajaybeniwal** [comment]
HI @gaearon I added react-stateless-wrapper to make test cases pass because of the below mentioned issue 
https://github.com/facebook/react/issues/4972

**Comment by timdorr** [comment]
I think I might take that as a ding against them right now. They should be testable without throwing in too many libraries.

**Comment by SimenB** [comment]
The wrapper is 12 lines of code though (https://github.com/ngerritsen/react-stateless-wrapper/blob/master/react-stateless-wrapper.js), and stateless components are a recommended pattern from FB.

> In an ideal world, most of your components would be stateless functions because these stateless components can follow a faster code path within the React core. This is the recommended pattern, when possible.

**Comment by sompylasar** [comment]
The react-stateless-wrapper misses this feature of React:
https://facebook.github.io/react/docs/context.html#referencing-context-in-stateless-functional-components

**Comment by urbanvikingr** [comment]
Heads up! I've a complete repo with the todo example https://github.com/urbanvikingr/todo which I'm currently updating the docs with together @gaearon .
I'll transfer the source code to this repo soon.

**Comment by timdorr** [comment]
Based on the work by the Dan's over in #1285, I'm going to close this in favor of the community effort going on over there. Feel free to join in!

**Pull request closed without merging**
