### PR TITLE
Add Server Rendering Recipe

### PR DESCRIPTION
**Pull request by hedgerh**
First draft of the Server Rendering recipe for the docs.  Appreciate all feedback, typo corrections, code corrections, and/or better explanations.  Will be working on the async section tonight.

### CODE REVIEW

**Comment by danmartinez101** [comment]
I think this would fit better in the react-redux project than in here. I work with a team heavily based on Angular at the moment, and while I'm an advocate for React, we are most likely going to be putting effort into an ng2.0 upgrade rather than migration to React. The more Redux is tied to React, the less interested non-React developers are going to be interested I fear and that would be a shame.

**Comment by gaearon** [comment]
Redux is not tied to React. These are just docs, and something that's often requested. If Angular 2 can render on the server, I'm happy to include both "Server Rendering with React" and "Server Rendering with Angular 2".

**Comment by danmartinez101** [comment]
I realized after your response that I wasn't clear about what I meant by "tied"; sorry about that.
I didn't mean to imply that Redux is tied to React in implementation. I meant more that the perception from the docs and examples is that Redux is tied to React. But yes, of course, Redux isn't actually tied to React.

**Comment by gaearon** [comment]
>I meant more that the perception from the docs and examples is that Redux is tied to React.

That's what I know! I'd be happy to see somebody contribute Angular docs.

**Comment by timdorr** [comment]
I've filled in most of the blanks over at hedgerh/redux#1. Let me know if there's anything else you wanted to see. 

@hedgerh should be able to merge downstream and get that stuff into this PR.

**Comment by timdorr** [comment]
Btw, some good discussion is going on in that PR. If anyone wants to join in, check it out.

**Comment by timdorr** [comment]
OK, everything's green and ready for review. How does this look @gaearon?

**Comment by hedgerh** [comment]
Hooray! We should squash down some of the smaller correction commits to keep things tidy

**Comment by gaearon** [comment]
omg that's good stuff, I love it.
:heart: @hedgerh @timdorr 

Anything that needs to be done here before merge? I don't mind a bunch of doc-only commits to be honest, so I'm fine with keeping them non-squashed.

**Comment by timdorr** [comment]
It's all good on my end now that the build is green :)

**Comment by hedgerh** [comment]
:+1:

**Comment by gaearon** [comment]
Hey, this is live, and awesome job.
http://rackt.github.io/redux/docs/recipes/ServerRendering.html

**Comment by timdorr** [comment]
Yayhooray! :tada:

**Pull request merged**
