### PR TITLE
Catch and rethrow error from reducer init in combineReducers #717

### PR DESCRIPTION
**Pull request by ellbee**

### CODE REVIEW

**Comment by gaearon** [comment]
Looks good to me. Can you please verify this fixes the original problem?

You can

1. Check out https://github.com/rackt/redux/pull/714
2. Introduce an error inside any reducer
3. Make sure DevTools now show the error

**Comment by ellbee** [comment]
Yep, I'm out for the day now but I'll get on it tomorrow.

**Comment by gaearon** [comment]
Confirm this issue is fixed.
I took the liberty to refactor a bit: https://github.com/rackt/redux/commit/a1485f0e30ea0ea5e023a6d0f5947bd56edff7dd
Thank you very much for your help here and on other projects.

**Comment by ellbee** [comment]
:+1: for the refactorings. 

And thank you for this awesome project. I am happy I could contribute something back.

**Pull request merged**
