### PR TITLE
Update ExampleTodoList.md

### PR DESCRIPTION
**Pull request by benny856694**
incorrect use of spread operator on object

### CODE REVIEW

**Comment by gaearon** [comment]
Would you mind also looking through other doc pages to make sure we don’t use object spread there unless specifically mentioning that it is a proposal?

**Comment by benny856694** [comment]
@gaearon , ok

**Comment by benny856694** [comment]
@gaearon , one more finding: [components/TodoList.js](http://redux.js.org/docs/basics/UsageWithReact.html).
I don't know why this code compiles but above code doesn't compile? should this code be corrected with expanded property?

**Comment by gaearon** [comment]
It works inside JSX because JSX already includes this syntax. So it is fine there.

**Pull request merged**
