### PR TITLE
README: added link for offline docs & instructions.

### PR DESCRIPTION
**Pull request by paulwittmann**
**Problem this solves**
+ I want to be able to read the docs on the train / when offline.

**How**
+ link to a repository with instructions on how to create offline docs and example exports (will not always be up-to-date).

**Why this way**
+ don't want to bloat this repo with PDF, mobi, ePub builds. We could add the build instructions in Redux's README.

**Ideas for an even better solution**
+ integrate links to up-to-date PDF, ePub & MOBI files into https://rackt.github.io/redux - didn't hear back from @gitbookIO how that's possible / whether it's in the works.
Mockup:
mockup
+ add cache manifest to gitbook - didn't hear back from @gitbookIO or @samypesse about why this doesn't seem to be present anymore!? [https://github.com/GitbookIO/gitbook/pull/171](https://github.com/GitbookIO/gitbook/pull/171)

### CODE REVIEW

**Comment by gaearon** [comment]
Thank you! We'll go with outsourcing PDF maintenance to you then. :-P

**Comment by paulwittmann** [comment]
great :) just pushed new versions here: [https://github.com/paulwittmann/redux-offline-docs](https://github.com/paulwittmann/redux-offline-docs)

**Comment by faergeek** [comment]
Would be cool to have a dash docset for redux
https://kapeli.com/docsets

**Comment by jjstrat3** [comment]
I'd like to second @faergeek 's comment.  I don't know how many folks who use Redux also use Dash, but it's an amazing way to view/annotate documentation offline for libraries, languages, and frameworks!

I don't know if you want me to file a new "issue" to track this, but I'd be happy to contribute by generating a docset for reading the Redux docs in Dash.  It's become such an indispensable tool for myself at least!

**Comment by gaearon** [comment]
I don’t really know what’s involved in doing that so feel free to explore it. :+1:

**Pull request merged**
