### PR TITLE
Set up redux.js.org CNAME

### LINKED ISSUE #890: Proposal: move docs to redux.js.org
There are two problems:

1. The official doc URL is kinda long (http://rackt.github.io/redux)
2. There is http://reduxjs.com which is unofficial and hosts outdated docs

I'd like to see both of these problems solved by moving to a free [.js.org](https://dns.js.org/) domain for the docs. That would be `redux.js.org`.

Ideally I'd like to see http://reduxjs.com (which is currently owned by @demohi, as per https://github.com/camsong/redux-in-chinese/issues/1#issue-101240158) redirect to the official docs. I understand the noble effort of Chinese translation, but a much more complete Chinese translation is available at http://camsong.github.io/redux-in-chinese/, and at this point http://reduxjs.com only confuses beginners who find outdated docs in Google and assume they are official.

@demohi Can I count on your help with this? We'd really appreciate setting up a redirect instead. I can prepare a PR to redirect every page, if you'd like.

Thoughts?

-----------------

- [x] Establish http://redux.js.org
- [x] Make sure it doesn't go away on next `npm run docs:publish`
- [ ] Redirect from http://rackt.github.io/redux/* to appropriate pages on redux.js.org
- [ ] Redirect from http://reduxjs.com/* to appropriate pages on redux.js.org
- [ ] Update links

### PR DESCRIPTION
**Pull request by timdorr**
As per [step 3 of the dns.js.org instructions](https://github.com/js-org/dns.js.org) and [github's documentation on CNAME files](https://help.github.com/articles/adding-a-cname-file-to-your-repository/).

Closes #890

### CODE REVIEW

**Comment by gaearon** [comment]
I wonder if it's going to be auto-deleted on next `npm run docs:publish`?

**Comment by timdorr** [comment]
Oh, it probably will. You may want to copy in @demohi's [addition to `package.json`](https://github.com/rackt/redux/pull/892/files)

**Comment by gaearon** [comment]
Would you mind doing that?

**Comment by timdorr** [comment]
Yeah, sure. I haven't built the docs before, so I'll do a full run through to be sure.

**Pull request merged**
