### PR TITLE
Add browserify config

### PR DESCRIPTION
**Pull request by e-jigsaw**
Replace `process.env.NODE_ENV` by adding this config when using browserify.

React also written this config: https://github.com/facebook/react/blob/0ce28c6e88448af6eda69df66088b88e7248bbb7/packages/react/package.json#L29-L33

Thanks

[Review on Reviewable](https://reviewable.io/reviews/rackt/redux/1301)

### CODE REVIEW

**Comment by gaearon** [comment]
Don't we also need to make it a dependency then?

**Comment by gaearon** [comment]
Also if we go with that, we need to add this to React Redux as well.

**Comment by e-jigsaw** [comment]
@gaearon 

> Don't we also need to make it a dependency then?

No, Just `"browserify": "..."`

> Also if we go with that, we need to add this to React Redux as well.

Yes, I will send same PR to react-redux if this PR merged

**Comment by timdorr** [comment]
LGTM and shouldn't hurt anything to add it. :+1:

**Comment by gaearon** [comment]
Thanks

**Comment by e-jigsaw** [comment]
@gaearon Thanks, I sent same PR to react-redux.

**Comment by gaearon** [comment]
Out in 3.1.0.

**Comment by gaearon** [comment]
FYI #1304

**Pull request merged**
