### PR TITLE
Implemented check for nextReducer in replaceReducer so that it thrown…

### PR DESCRIPTION
**Pull request by JamieDixon**
…s when not a function. Test included.

Fixes https://github.com/rackt/redux/issues/1318 including unit test.

### CODE REVIEW

**Comment by gaearon** [comment]
Why does it not allow me to merge from web interface? Is your fork up to date?

**Comment by JamieDixon** [comment]
I just took the fork a moment ago but I'll check everything now.

**Comment by gaearon** [comment]
You probably forked before, previous commit is in October.
Need to rebase on the recent master.

**Comment by gaearon** [comment]
Thank you for the effort. I went ahead and merged #1321 — it didn’t have conflicts.
Keep an eye on the repo, we may have more low-hanging fruit later!

**Comment by JamieDixon** [comment]
Glad the issue is resolved Dan. Surprised by how upset I feel that I missed out here. Very unexpected. I'm new to OSS. Perhaps this is normal :) Time to reflect.

**Comment by gaearon** [comment]
You found another good one :-)

**Pull request closed without merging**
