### PR TITLE
[use Set instead of Array]

### PR DESCRIPTION
**Pull request by AntouanK**
- replace an Array with a Set ( ES2015 )

Since you use babel and all of the ES2015 goodies, I was wondering why not use things like `Set` and `Map`. 
They will be more perfomant on browsers that support them natively, and developer wise, I think they have a nicer API to work with, than plain old Arrays.

### CODE REVIEW

**Comment by gaearon** [comment]
We don't want to force the consumer to use Polyfills.

**Comment by AntouanK** [comment]
But you already use babel to "transpile" it. Doesn't it convert that to ES5?

**Comment by dbrans** [comment]
babel transpiles syntax only.

**Comment by gaearon** [comment]
Babel only converts the syntax. Something with runtime behavior (e.g. `Set`) needs to be polyfilled. Babel includes a polyfill, but it's fairly large, and not worth it for Redux.

**Comment by gaearon** [comment]
To clarify—using a polyfill can be a valid choice for a larger project. However Redux is purposefully tiny (~2KB). So we don't want to grow beyond that just to use new features.

**Comment by AntouanK** [comment]
Oh I see. Ok, that makes sense.
Including the polyfill makes it 19KB, it's a big difference.

**Pull request closed without merging**
