### PR TITLE
be more explicit when importing files

### PR DESCRIPTION
**Pull request by 6ewis**
It's minor but it's helpful when someone try to follow the code. In addition, there's no point importing files we do not use.

### CODE REVIEW

**Comment by johanneslumpe** [comment]
I feel that adding a `/` at the end should be enough to signal to a user that we are importing the index file of a directory.

**Comment by 6ewis** [comment]
@johanneslumpe In this instance what's the cost of being more explicit when we can avoid subtle confusion? nothing. It did confuse me while trying to grok redux.

**Comment by johanneslumpe** [comment]
@6ewis To me it is just superfluous because a slash already makes the intention clear. But I will let others decide what the direction should be here. I agree though that having nothing at the end so that it looks like a file require is definitely not great.

**Comment by omnidan** [comment]
I think it makes sense to explicitly state we import `index`, but we should at least add a `/` at the end.

**Comment by gaearon** [comment]
We use this convention all over the place, including the docs.
I'd say we either do it one way, or the other way, but doing it only in one place is inconsistent.

**Comment by gaearon** [comment]
I reverted—again, I don't mind the change, but only as a big commit fixing it all over the docs. :wink:

**Pull request merged**
